"""initial schema

Revision ID: 3c48ee49b222
Revises: 
Create Date: 2026-08-19 09:48:06.109600
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '3c48ee49b222'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector must exist before the embeddings table is created.  IF NOT EXISTS makes
    # this a no-op where an operator (or docker/postgres/init.sql) already created it;
    # on a managed database that forbids CREATE EXTENSION, run it once by hand first.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'STARTER', 'GROWTH', 'ENTERPRISE', name='orgplan', native_enum=False, length=32), nullable=False),
    sa.Column('own_company_name', sa.String(length=120), nullable=True),
    sa.Column('own_company_url', sa.String(length=2048), nullable=True),
    sa.Column('own_company_description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_organization_id_created_at', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_table('comparisons',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('competitor_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_comparisons_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_comparisons_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comparisons'))
    )
    op.create_index('ix_comparisons_organization_id_created_at', 'comparisons', ['organization_id', 'created_at'], unique=False)
    op.create_table('competitors',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('website_url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('favicon_url', sa.String(length=2048), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='competitorstatus', native_enum=False, length=32), nullable=False),
    sa.Column('importance', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='importance', native_enum=False, length=32), nullable=False),
    sa.Column('monitoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('monitoring_interval_hours', sa.Integer(), nullable=False),
    sa.Column('next_monitor_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_overall_score', sa.Float(), nullable=True),
    sa.Column('latest_analysis_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_competitors_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_competitors_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitors')),
    sa.UniqueConstraint('organization_id', 'domain', name='uq_competitors_organization_id_domain')
    )
    op.create_index(op.f('ix_competitors_next_monitor_at'), 'competitors', ['next_monitor_at'], unique=False)
    op.create_index('ix_competitors_organization_id_created_at', 'competitors', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_competitors_organization_id_status', 'competitors', ['organization_id', 'status'], unique=False)
    op.create_table('invitations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_invitations_invited_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_invitations_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations'))
    )
    op.create_index('ix_invitations_organization_id_email', 'invitations', ['organization_id', 'email'], unique=False)
    op.create_index(op.f('ix_invitations_token_hash'), 'invitations', ['token_hash'], unique=False)
    op.create_table('memberships',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_memberships_organization_id_user_id')
    )
    op.create_index('ix_memberships_user_id', 'memberships', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('jti', name=op.f('uq_refresh_tokens_jti'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('ix_refresh_tokens_user_id_expires_at', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_table('reports',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.Enum('COMPETITOR_OVERVIEW', 'COMPARISON', 'WEEKLY_INTELLIGENCE', 'MONTHLY_COMPETITIVE', name='reporttype', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_reports_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_reports_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index('ix_reports_organization_id_created_at', 'reports', ['organization_id', 'created_at'], unique=False)
    op.create_table('usage_counters',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('analyses_used', sa.Integer(), nullable=False),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('ai_tokens_in', sa.Integer(), nullable=False),
    sa.Column('ai_tokens_out', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_usage_counters_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_counters')),
    sa.UniqueConstraint('organization_id', 'period', name='uq_usage_counters_organization_id_period')
    )
    op.create_table('verification_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Enum('EMAIL_VERIFICATION', 'PASSWORD_RESET', name='verificationpurpose', native_enum=False, length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_verification_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_tokens'))
    )
    op.create_index(op.f('ix_verification_tokens_token_hash'), 'verification_tokens', ['token_hash'], unique=False)
    op.create_index('ix_verification_tokens_user_id_purpose', 'verification_tokens', ['user_id', 'purpose'], unique=False)
    op.create_table('alert_rules',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('competitor_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('change_types', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('min_severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='severity', native_enum=False, length=16), nullable=False),
    sa.Column('channels', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('webhook_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_alert_rules_competitor_id_competitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_alert_rules_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_alert_rules_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_index('ix_alert_rules_organization_id_is_active', 'alert_rules', ['organization_id', 'is_active'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=True),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.Enum('FULL_ANALYSIS', 'REFRESH', 'COMPARISON', 'REPORT', name='jobtype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('depth', sa.Enum('QUICK', 'STANDARD', 'DEEP', name='analysisdepth', native_enum=False, length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_analysis_jobs_competitor_id_competitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_analysis_jobs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_analysis_jobs_triggered_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_jobs'))
    )
    op.create_index(op.f('ix_analysis_jobs_celery_task_id'), 'analysis_jobs', ['celery_task_id'], unique=False)
    op.create_index('ix_analysis_jobs_competitor_id_status', 'analysis_jobs', ['competitor_id', 'status'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_idempotency_key'), 'analysis_jobs', ['idempotency_key'], unique=False)
    op.create_index('ix_analysis_jobs_organization_id_created_at', 'analysis_jobs', ['organization_id', 'created_at'], unique=False)
    op.create_table('competitor_pages',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('page_type', sa.Enum('HOME', 'PRICING', 'PRODUCT', 'FEATURES', 'ABOUT', 'BLOG', 'CASE_STUDY', 'DOCS', 'CONTACT', 'CAREERS', 'LEGAL', 'OTHER', name='pagetype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('discovery_score', sa.Float(), nullable=False),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_competitor_pages_competitor_id_competitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_competitor_pages_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitor_pages')),
    sa.UniqueConstraint('competitor_id', 'url_hash', name='uq_competitor_pages_competitor_id_url_hash')
    )
    op.create_index('ix_competitor_pages_competitor_id_page_type', 'competitor_pages', ['competitor_id', 'page_type'], unique=False)
    op.create_table('embeddings',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_embeddings_competitor_id_competitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_embeddings_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embeddings'))
    )
    op.create_index('ix_embeddings_competitor_id_source_type', 'embeddings', ['competitor_id', 'source_type'], unique=False)
    op.create_index(op.f('ix_embeddings_content_hash'), 'embeddings', ['content_hash'], unique=False)
    op.create_table('seo_snapshots',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('pages_discovered', sa.Integer(), nullable=False),
    sa.Column('has_sitemap', sa.Boolean(), nullable=False),
    sa.Column('sitemap_url_count', sa.Integer(), nullable=True),
    sa.Column('has_robots_txt', sa.Boolean(), nullable=False),
    sa.Column('has_blog', sa.Boolean(), nullable=False),
    sa.Column('pages_missing_title', sa.Integer(), nullable=False),
    sa.Column('pages_missing_meta_description', sa.Integer(), nullable=False),
    sa.Column('pages_missing_h1', sa.Integer(), nullable=False),
    sa.Column('avg_title_length', sa.Float(), nullable=True),
    sa.Column('avg_word_count', sa.Float(), nullable=True),
    sa.Column('internal_link_count', sa.Integer(), nullable=False),
    sa.Column('external_link_count', sa.Integer(), nullable=False),
    sa.Column('structured_data_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_seo_snapshots_competitor_id_competitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_seo_snapshots_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seo_snapshots'))
    )
    op.create_index('ix_seo_snapshots_competitor_id_captured_at', 'seo_snapshots', ['competitor_id', 'captured_at'], unique=False)
    op.create_table('analyses',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('prompt_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('depth', sa.Enum('QUICK', 'STANDARD', 'DEEP', name='analysisdepth', native_enum=False, length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('positioning', sa.Text(), nullable=True),
    sa.Column('target_audience', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('value_propositions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('marketing_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('data_completeness', sa.Float(), nullable=True),
    sa.Column('pages_analyzed', sa.Integer(), nullable=False),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('injection_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_analyses_competitor_id_competitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], name=op.f('fk_analyses_job_id_analysis_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_analyses_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    op.create_index('ix_analyses_competitor_id_created_at', 'analyses', ['competitor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analyses_content_fingerprint'), 'analyses', ['content_fingerprint'], unique=False)
    op.create_index('ix_analyses_organization_id_created_at', 'analyses', ['organization_id', 'created_at'], unique=False)
    op.create_table('page_snapshots',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.String(length=2048), nullable=True),
    sa.Column('lang', sa.String(length=16), nullable=True),
    sa.Column('headings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('open_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detected_prices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calls_to_action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('render_mode', sa.String(length=16), nullable=False),
    sa.Column('fetch_duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_page_snapshots_competitor_id_competitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_page_snapshots_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['competitor_pages.id'], name=op.f('fk_page_snapshots_page_id_competitor_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_snapshots'))
    )
    op.create_index('ix_page_snapshots_competitor_id_fetched_at', 'page_snapshots', ['competitor_id', 'fetched_at'], unique=False)
    op.create_index('ix_page_snapshots_page_id_fetched_at', 'page_snapshots', ['page_id', 'fetched_at'], unique=False)
    op.create_index(op.f('ix_page_snapshots_text_hash'), 'page_snapshots', ['text_hash'], unique=False)
    op.create_table('changes',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('change_type', sa.Enum('PRICE_INCREASED', 'PRICE_DECREASED', 'PLAN_ADDED', 'PLAN_REMOVED', 'PRODUCT_ADDED', 'PRODUCT_REMOVED', 'FEATURE_ADDED', 'FEATURE_REMOVED', 'POSITIONING_CHANGED', 'CONTENT_CHANGED', 'PAGE_ADDED', 'PAGE_REMOVED', 'SCORE_CHANGED', name='changetype', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='severity', native_enum=False, length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_key', sa.String(length=200), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_changes_analysis_id_analyses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_changes_competitor_id_competitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_changes_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_changes'))
    )
    op.create_index('ix_changes_competitor_id_detected_at', 'changes', ['competitor_id', 'detected_at'], unique=False)
    op.create_index('ix_changes_organization_id_detected_at', 'changes', ['organization_id', 'detected_at'], unique=False)
    op.create_index('ix_changes_organization_id_severity', 'changes', ['organization_id', 'severity'], unique=False)
    op.create_table('pricing_plans',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('normalized_name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('billing_period', sa.Enum('MONTHLY', 'YEARLY', 'ONE_TIME', 'USAGE_BASED', 'UNKNOWN', name='billingperiod', native_enum=False, length=32), nullable=False),
    sa.Column('is_custom_pricing', sa.Boolean(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source', sa.Enum('OBSERVED', 'AI_INFERENCE', name='datasource', native_enum=False, length=32), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_pricing_plans_analysis_id_analyses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_pricing_plans_competitor_id_competitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_pricing_plans_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_plans')),
    sa.UniqueConstraint('competitor_id', 'normalized_name', 'billing_period', name='uq_pricing_plans_competitor_id_normalized_name_billing_period')
    )
    op.create_index('ix_pricing_plans_competitor_id_is_current', 'pricing_plans', ['competitor_id', 'is_current'], unique=False)
    op.create_table('products',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source', sa.Enum('OBSERVED', 'AI_INFERENCE', name='datasource', native_enum=False, length=32), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_products_analysis_id_analyses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_products_competitor_id_competitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_products_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('competitor_id', 'normalized_name', name='uq_products_competitor_id_normalized_name')
    )
    op.create_index('ix_products_competitor_id_is_current', 'products', ['competitor_id', 'is_current'], unique=False)
    op.create_table('scores',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('threat_level', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('data_completeness', sa.Float(), nullable=True),
    sa.Column('methodology_version', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_scores_analysis_id_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_scores_competitor_id_competitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_scores_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scores'))
    )
    op.create_index('ix_scores_competitor_id_created_at', 'scores', ['competitor_id', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('alert_rule_id', sa.UUID(), nullable=True),
    sa.Column('change_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'WEBHOOK', name='notificationchannel', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'READ', name='notificationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], name=op.f('fk_notifications_alert_rule_id_alert_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], name=op.f('fk_notifications_change_id_changes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_notifications_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_organization_id_created_at', 'notifications', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_organization_id_status', 'notifications', ['organization_id', 'status'], unique=False)
    # ### end Alembic commands ###


    # Approximate nearest-neighbour index for semantic search.  Created after the table
    # so the row count is known to be zero; lists=100 suits the low-hundred-thousands of
    # chunks this schema expects, and should be revisited if that grows by an order of
    # magnitude.  Cosine distance, matching the operator used by the search service.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_embeddings_embedding_cosine "
        "ON embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_embeddings_embedding_cosine")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_organization_id_status', table_name='notifications')
    op.drop_index('ix_notifications_organization_id_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_scores_competitor_id_created_at', table_name='scores')
    op.drop_table('scores')
    op.drop_index('ix_products_competitor_id_is_current', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_pricing_plans_competitor_id_is_current', table_name='pricing_plans')
    op.drop_table('pricing_plans')
    op.drop_index('ix_changes_organization_id_severity', table_name='changes')
    op.drop_index('ix_changes_organization_id_detected_at', table_name='changes')
    op.drop_index('ix_changes_competitor_id_detected_at', table_name='changes')
    op.drop_table('changes')
    op.drop_index(op.f('ix_page_snapshots_text_hash'), table_name='page_snapshots')
    op.drop_index('ix_page_snapshots_page_id_fetched_at', table_name='page_snapshots')
    op.drop_index('ix_page_snapshots_competitor_id_fetched_at', table_name='page_snapshots')
    op.drop_table('page_snapshots')
    op.drop_index('ix_analyses_organization_id_created_at', table_name='analyses')
    op.drop_index(op.f('ix_analyses_content_fingerprint'), table_name='analyses')
    op.drop_index('ix_analyses_competitor_id_created_at', table_name='analyses')
    op.drop_table('analyses')
    op.drop_index('ix_seo_snapshots_competitor_id_captured_at', table_name='seo_snapshots')
    op.drop_table('seo_snapshots')
    op.drop_index(op.f('ix_embeddings_content_hash'), table_name='embeddings')
    op.drop_index('ix_embeddings_competitor_id_source_type', table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index('ix_competitor_pages_competitor_id_page_type', table_name='competitor_pages')
    op.drop_table('competitor_pages')
    op.drop_index('ix_analysis_jobs_organization_id_created_at', table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_idempotency_key'), table_name='analysis_jobs')
    op.drop_index('ix_analysis_jobs_competitor_id_status', table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_celery_task_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index('ix_alert_rules_organization_id_is_active', table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index('ix_verification_tokens_user_id_purpose', table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_token_hash'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_table('usage_counters')
    op.drop_index('ix_reports_organization_id_created_at', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_refresh_tokens_user_id_expires_at', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_memberships_user_id', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_invitations_token_hash'), table_name='invitations')
    op.drop_index('ix_invitations_organization_id_email', table_name='invitations')
    op.drop_table('invitations')
    op.drop_index('ix_competitors_organization_id_status', table_name='competitors')
    op.drop_index('ix_competitors_organization_id_created_at', table_name='competitors')
    op.drop_index(op.f('ix_competitors_next_monitor_at'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index('ix_comparisons_organization_id_created_at', table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_index('ix_audit_logs_organization_id_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
